# Generated by Django 4.2.1 on 2023-05-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Home name')),
                ('about', models.TextField(verbose_name='Home text')),
                ('button_name', models.CharField(max_length=60, verbose_name='Home button name')),
                ('img', models.ImageField(upload_to='home_images', verbose_name='Home image')),
            ],
        ),
    ]
