# Generated by Django 4.2.1 on 2023-05-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='logo',
            field=models.ImageField(blank=True, upload_to='home_images', verbose_name='Home logo'),
        ),
    ]
