# Generated by Django 4.2.1 on 2023-05-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_home_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Project name')),
                ('img1', models.ImageField(upload_to='projects_images', verbose_name='Project image1')),
                ('img2', models.ImageField(upload_to='projects_images', verbose_name='Project image2')),
                ('img3', models.ImageField(upload_to='projects_images', verbose_name='Project image3')),
            ],
        ),
    ]
